---
abstract: 'Plain text training material for bots like L<Hailo> and L<AI::MegaHAL>'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  File::Slurp: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  lib: '0'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bot-Training
no_index:
  directory:
    - t
requires:
  Any::Moose: '0'
  Class::Load: '0'
  Dir::Self: '0'
  Encode: '0'
  File::ShareDir: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Module::Pluggable: '0'
  Moose: '0'
  MooseX::Getopt::Dashes: '0'
  Pod::Usage: '0'
  autodie: '0'
  namespace::clean: '0'
  open: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Bot-Training
  homepage: http://metacpan.org/release/Bot-Training
  license: http://dev.perl.org/licenses/
  repository: git://github.com/avar/bot-training.git
version: '0.06'
x_authority: cpan:AVAR
