---
abstract: 'Plain text training material for bots like L<Hailo> and L<AI::MegaHAL>'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  File::Find: 0
  File::Slurp: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101290'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Training
no_index:
  directory:
    - t
recommends: {}
requires:
  Any::Moose: 0
  Class::MOP: 0
  Dir::Self: 0
  Encode: 0
  File::ShareDir: 0
  File::Spec::Functions: 0
  List::Util: 0
  Module::Pluggable: 0
  Moose: 0
  MooseX::Getopt::Dashes: 0
  Mouse: 0
  MouseX::Getopt::Dashes: 0
  Pod::Usage: 0
  autodie: 0
  namespace::clean: 0
  open: 0
  perl: 5.010
resources:
  Ratings: http://cpanratings.perl.org/d/Bot-Training
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Bot-Training
  homepage: http://search.cpan.org/dist/Bot-Training/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avar/bot-training
version: 0.04
